server:
  port: 8090

logging:
  file:
    path: logs

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mapper/*Mapper.xml

spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    name: sflc
    #dev
    #    url: jdbc:oracle:thin:@172.16.102.10:1521:prod
    #    url: jdbc:oracle:thin:@211.151.130.55:1521:prod
    #    username: sflcgood200313
    #    password: sflcgood200313
    #pro
    #url: jdbc:oracle:thin:@172.16.102.181:1521:sflcdb2
    url: jdbc:oracle:thin:@211.151.130.26:41626:sflcdb2
#   url: jdbc:oracle:thin:@(DESCRIPTION =(ADDRESS = (PROTOCOL = TCP)(HOST = 172.16.102.182)(PORT = 1521))(ADDRESS = (PROTOCOL = TCP)(HOST = 172.16.102.183)(PORT = 1521))(LOAD_BALANCE = yes)(FAILOVER = ON)(CONNECT_DATA =(SERVER = DEDICATED)(SERVICE_NAME = sflcdb)(FAILOVER_MODE=(TYPE = SELECT)(METHOD = BASIC)(RETIRES = 20)(DELAY = 15))))
    username: sflcgood
    password: sflcgood
    type: com.alibaba.druid.pool.DruidDataSource
